export const FAKE_POPULARS = [
  {
    backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
    first_air_date: "2022-09-21",
    genre_ids: [18, 80],
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
    popularity: 6817.15,
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    vote_average: 5.3,
    vote_count: 591,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
    id: 83867,
    name: "Star Wars: Andor",
    original_language: "en",
    original_name: "Star Wars: Andor",
    overview:
      "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
    poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 10768],
    popularity: 1066.084,
    first_air_date: "2022-09-21",
    vote_average: 7.926,
    vote_count: 115,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/eqhKMZTLcieAvoH6CBqknTTfNby.jpg",
    id: 90802,
    name: "The Sandman",
    original_language: "en",
    original_name: "The Sandman",
    overview:
      "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.",
    poster_path: "/q54qEgagGOYCq5D1903eBVMNkbo.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 596.192,
    first_air_date: "2022-08-05",
    vote_average: 8.163,
    vote_count: 1048,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/a906PH7CDmSOdS7kmnAgdWk5mhv.jpg",
    id: 67744,
    name: "Mindhunter",
    original_language: "en",
    original_name: "Mindhunter",
    overview:
      "An agent in the FBI's Elite Serial Crime Unit develops profiling techniques as he pursues notorious serial killers and rapists.",
    poster_path: "/fbKE87mojpIETWepSbD5Qt741fp.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 90.285,
    first_air_date: "2017-10-13",
    vote_average: 8.029,
    vote_count: 1733,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/nGfjgUlES2WuYrHXNNF4fbGe2Eq.jpg",
    id: 89456,
    name: "Primal",
    original_language: "en",
    original_name: "Primal",
    overview:
      "A caveman forms a bond with a dinosaur as they struggle to survive in a hostile world.",
    poster_path: "/jflPzxYbM4MxxCppo2AbvSbTOLm.jpg",
    media_type: "tv",
    genre_ids: [10759, 16, 18],
    popularity: 137.901,
    first_air_date: "2019-10-08",
    vote_average: 8.695,
    vote_count: 1055,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/aZ4mBxYHrKHFu9QpUmpVDIOoWAb.jpg",
    id: 155537,
    name: "Black Bird",
    original_language: "en",
    original_name: "Black Bird",
    overview:
      "As Jimmy Keene begins a 10-year prison sentence, he gets an incredible offer: If he can elicit a confession from suspected killer Larry Hall, Jimmy will be freed. Completing this mission becomes the challenge of a lifetime.",
    poster_path: "/79M2yNSmkh4CCMrWNV6b2xvIeNn.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 215.673,
    first_air_date: "2022-07-07",
    vote_average: 8.196,
    vote_count: 168,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lfQnJr9ugRKtl3vhG6IfOOAhN8s.jpg",
    id: 197067,
    name: "Extraordinary Attorney Woo",
    original_language: "ko",
    original_name: "이상한 변호사 우영우",
    overview:
      "Brilliant attorney Woo Young-woo tackles challenges in the courtroom and beyond as a newbie at a top law firm and a woman on the autism spectrum.",
    poster_path: "/zuNOQVI4rEaqwknrfQUVKtlKE2C.jpg",
    media_type: "tv",
    genre_ids: [18, 35],
    popularity: 131.501,
    first_air_date: "2022-06-29",
    vote_average: 8.272,
    vote_count: 344,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/cImIRobqw7AGr7c2s1vX5BgLy7v.jpg",
    id: 108664,
    name: "Five Days at Memorial",
    original_language: "en",
    original_name: "Five Days at Memorial",
    overview:
      "Based on actual events from Hurricane Katrina. When the floodwaters rose, power failed, and heat soared, exhausted caregivers at a New Orleans hospital were forced to make profound, heart-wrenching decisions.",
    poster_path: "/yLx44hdSpt9GhP67JafP5sMEoMB.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 262.304,
    first_air_date: "2022-08-11",
    vote_average: 7.796,
    vote_count: 49,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/900tHlUYUkp7Ol04XFSoAaEIXcT.jpg",
    id: 87108,
    name: "Chernobyl",
    original_language: "en",
    original_name: "Chernobyl",
    overview:
      "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 77.173,
    first_air_date: "2019-05-06",
    vote_average: 8.603,
    vote_count: 4384,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/eljErfkQUcFUgQkI4I1soZcH8MW.jpg",
    id: 92783,
    name: "She-Hulk: Attorney at Law",
    original_language: "en",
    original_name: "She-Hulk: Attorney at Law",
    overview:
      "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    poster_path: "/3qO7wycn6o0lUJf15dupMFbEBTY.jpg",
    media_type: "tv",
    genre_ids: [35, 10765],
    popularity: 4815.281,
    first_air_date: "2022-08-18",
    vote_average: 7.033,
    vote_count: 903,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/33j33midGw49BBxiqlNZeZ6PZ0O.jpg",
    id: 85271,
    name: "WandaVision",
    original_language: "en",
    original_name: "WandaVision",
    overview:
      "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
    poster_path: "/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 18],
    popularity: 138.069,
    first_air_date: "2021-01-15",
    vote_average: 8.314,
    vote_count: 10501,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/whWHhs6p1YVMKDsH9yuvF2KR64d.jpg",
    id: 115004,
    name: "Mare of Easttown",
    original_language: "en",
    original_name: "Mare of Easttown",
    overview:
      "A detective in a small Pennsylvania town investigates a local murder while trying to keep her life from falling apart.",
    poster_path: "/78aK4Msbr22A5PGa6PZV0pAvdwf.jpg",
    media_type: "tv",
    genre_ids: [18, 9648, 80],
    popularity: 39.028,
    first_air_date: "2021-04-18",
    vote_average: 8.284,
    vote_count: 844,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/8V1XPEDLtJoxOWlE6gYzn2sQaMp.jpg",
    id: 60574,
    name: "Peaky Blinders",
    original_language: "en",
    original_name: "Peaky Blinders",
    overview:
      "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
    poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 676.775,
    first_air_date: "2013-09-12",
    vote_average: 8.6,
    vote_count: 7527,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/8kBhAP03JpPcTklJp5idCNJhRqE.jpg",
    id: 1413,
    name: "American Horror Story",
    original_language: "en",
    original_name: "American Horror Story",
    overview:
      "An anthology horror drama series centering on different characters and locations, including a house with a murderous past, an asylum, a witch coven, a freak show, a hotel, a farmhouse in Roanoke, a cult, the apocalypse and a summer camp.",
    poster_path: "/kxtWasoZ7Q92erTJuuRtZiXTPiH.jpg",
    media_type: "tv",
    genre_ids: [18, 9648, 10765],
    popularity: 785.613,
    first_air_date: "2011-10-05",
    vote_average: 8.147,
    vote_count: 4697,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 4226.025,
    first_air_date: "2022-08-21",
    vote_average: 8.6,
    vote_count: 1623,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zNugnnR5KEmq9EzLcl0Me1UmHYk.jpg",
    id: 120089,
    name: "SPY x FAMILY",
    original_language: "ja",
    original_name: "SPY×FAMILY",
    overview:
      "Master spy Twilight is the best at what he does when it comes to going undercover on dangerous missions in the name of a better world. But when he receives the ultimate impossible assignment—get married and have a kid—he may finally be in over his head! Not one to depend on others, Twilight has his work cut out for him procuring both a wife and a child for his mission to infiltrate an elite private school. What he doesn't know is that the wife he's chosen is an assassin and the child he's adopted is a telepath!",
    poster_path: "/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10759],
    popularity: 959.371,
    first_air_date: "2022-04-09",
    vote_average: 8.698,
    vote_count: 784,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 5307.068,
    first_air_date: "2022-09-01",
    vote_average: 7.7,
    vote_count: 965,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bY17tTK5GOEwxIValL0MBHGt6T6.jpg",
    id: 13916,
    name: "Death Note",
    original_language: "ja",
    original_name: "DEATH NOTE",
    overview:
      "Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?",
    poster_path: "/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 10765],
    popularity: 94.374,
    first_air_date: "2006-10-04",
    vote_average: 8.653,
    vote_count: 3057,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
    id: 44217,
    name: "Vikings",
    original_language: "en",
    original_name: "Vikings",
    overview:
      "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    poster_path: "/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10768],
    popularity: 406.946,
    first_air_date: "2013-03-03",
    vote_average: 8.082,
    vote_count: 5724,
    origin_country: ["CA"],
  },
  {
    adult: false,
    backdrop_path: "/yqZ5ACKeNJ30mylUEzvtWZu4pGU.jpg",
    id: 67116,
    name: "Lethal Weapon",
    original_language: "en",
    original_name: "Lethal Weapon",
    overview:
      "A slightly unhinged former Navy SEAL lands a job as a police officer in Los Angeles where he's partnered with a veteran detective trying to keep maintain a low stress level in his life.",
    poster_path: "/jbMZkxLHVDSKiZh0HppCthRW96k.jpg",
    media_type: "tv",
    genre_ids: [10759, 80, 18],
    popularity: 78.873,
    first_air_date: "2016-09-21",
    vote_average: 7.318,
    vote_count: 584,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    id: 1668,
    name: "Friends",
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 282.626,
    first_air_date: "1994-09-22",
    vote_average: 8.453,
    vote_count: 6161,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rsJyq5B2UApvLDTtH5nUwUBzQ1O.jpg",
    id: 128095,
    name: "Under the Banner of Heaven",
    original_language: "en",
    original_name: "Under the Banner of Heaven",
    overview:
      "A devout detective's faith is tested as he investigates a brutal murder that seems to be connected to an esteemed Utah family's spiral into LDS fundamentalism and their distrust in the government.",
    poster_path: "/gKyXUkyKRg9LdZzZWRzk0eKD5HJ.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 130.548,
    first_air_date: "2022-04-28",
    vote_average: 7.924,
    vote_count: 112,
    origin_country: ["US"],
  },
];
